### ISSUE TITLE
Crash on initial authentication call

### ISSUE THREAD

**Issue by maximilionus** [maximilionus/hurocon#2]
### About
Tool will crash on initial authentication command call. Configuration file **will** be generated without being filled with all provided information before the crash. This behavior kinda sus 🤔

### Details:
- Tool version: `0.4.5`-`0.5.0dev0`
- Python version: `3.9.13x64`
- Tested with: `poetry`, `pip`, `pipx`, native python virtual environment

### How to reproduce
1. Fresh install the tool, erase the config dir (`~/.config/hurocon/`)
2. Run initial authentication command:
   ```bash
   $ hurocon auth login
   ```
3. Input all requested data and confirm input
4. Get the raised exception traceback

### Traceback
```py
Traceback (most recent call last):
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\Scripts\hurocon", line 2, in <module>
    from hurocon import __main__
  File "E:\code\py\hurocon\hurocon\__main__.py", line 4, in <module>
    run_cli()
  File "E:\code\py\hurocon\hurocon\cli\__init__.py", line 8, in run_cli
    cli()
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\code\py\hurocon\hurocon\cli\auth.py", line 16, in auth_login
    auth_impl.auth_login_impl()
  File "E:\code\py\hurocon\hurocon\implementation\auth_impl.py", line 21, in auth_login_impl
    auth_cfg = AuthConfig()
  File "E:\code\py\hurocon\hurocon\core\local_cfg.py", line 67, in __init__
    self.__cfg = LocalConfig()
  File "E:\code\py\hurocon\hurocon\core\local_cfg.py", line 21, in __init__
    self.__check_updates()
  File "E:\code\py\hurocon\hurocon\core\local_cfg.py", line 27, in __check_updates
    local_version = self['config_version']
  File "C:\Users\MAXIMILI\AppData\Local\pypoetry\Cache\virtualenvs\hurocon-3sf-LoFd-py3.9\lib\site-packages\serialix\core.py", line 70, in __getitem__
    return self.__parsed_dict[key]
KeyError: 'config_version'
```

**Comment by maximilionus** [comment]
Issue was related to the dependency package, used for configuration files handling - [`serialix`](https://github.com/maximilionus/serialix). 😶

**Comment by maximilionus** [comment]
Fixed in [`serialix`](https://github.com/maximilionus/serialix) `"^2.4.1"`. Will lock the minimal allowed version to this one in `0.5.0` release. For the old releases, there's only one way to fix this issue - update the project dependencies 😅
